#!/usr/bin/python
import json

data = { 'ahello' : 1, 'b' : 2, 'c' : 3, 'd' : 4, 'e' : 5 }

json = json.dumps(data)
print("data convert to json")
print type(json)
text = json.loads(json)
print("json convert to data")
print text

